### ISSUE TITLE
does this support arm64?

### ISSUE THREAD

**Issue by ytfrdfiw** [yasukata/zpoline#6]
does this support arm64?thank you

**Comment by yasukata** [comment]
Thanks for your interest.

This implementation is for x86-64 and does not work on ARM.

**Comment by ytfrdfiw** [comment]
thank you for your reply




***@***.***
 
From: yasukata
Date: 2023-06-13 08:30
To: yasukata/zpoline
CC: ytfrdfiw; Author
Subject: Re: [yasukata/zpoline] does this support arm64? (Issue #6)
Thanks for your interest.
This implementation is for x86-64 and does not work on ARM.
