### ISSUE TITLE
can i get a copy of your paper

### ISSUE THREAD

**Issue by Ekkosun** [yasukata/zpoline#7]
hi, i'm interested in this hook and want to know the principle . But i can not find the paper in the site given. Can i get a copy of the your paper?
my email address is swj22@mails.tsinghua.edu.cn

**Comment by yasukata** [comment]
Thank you for your interest.

I found that I removed the explanation of the mechanism during the previous document maintenance and currently this repository does not have documentation describing how it works.

Therefore, I copied the texts from the design section of the paper to [Documentation/README.md](https://github.com/yasukata/zpoline/tree/master/Documentation#the-core-idea-october-2021); the commit is found [here](https://github.com/yasukata/zpoline/commit/a83527f1b2f5ae5f32f0ac5b1b5143931d57b642).

Thank you for letting me know about the issue of the documentation.

**Comment by Ekkosun** [comment]
thank you for your attention
